/* eslint-disable quote-props */
/* eslint-disable max-len */
/**
 * Translation file for this resource.
 *
 * This file is generated by combining automatic extraction and manual translations:
 * - The "en" (English) section is automatically extracted from source files
 * - Other language sections can be manually translated or pulled from Transifex
 * - When regenerating, existing manual translations are preserved when the English
 *   source text hasn't changed
 *
 * Structure:
 * - interface: translations for name/description (used by GUI formatMessage)
 * - extensions: translations for extension blocks (used by VM formatMessage)
 * - blocks: translations for Blockly blocks (used by Blockly.Msg)
 */

export default {
    'interface': {
        'en': {
            'microPythonEsp8266.description': 'Low-cost Wi-Fi SOC control board.'
        },
        'ru': {
            'microPythonEsp8266.description': 'Недорогая плата Wi-Fi  для управления'
        },
        'zh-cn': {
            'microPythonEsp8266.description': '低功耗 Wi-Fi SOC 控制板。'
        },
        'zh-tw': {
            'microPythonEsp8266.description': '低功耗 Wi-Fi SOC 控制板。'
        }
    },
    'extensions': {
        'en': {
            'microPythonEsp8266.modeMenu.input': 'input',
            'microPythonEsp8266.modeMenu.output': 'output',
            'microPythonEsp8266.modeMenu.inputPullup': 'input-pullup',
            'microPythonEsp8266.levelMenu.high': 'high',
            'microPythonEsp8266.levelMenu.low': 'low',
            'microPythonEsp8266.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonEsp8266.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonEsp8266.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonEsp8266.eolMenu.warp': 'warp',
            'microPythonEsp8266.eolMenu.noWarp': 'no-warp',
            'microPythonEsp8266.category.pins': 'Pins',
            'microPythonEsp8266.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonEsp8266.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonEsp8266.pins.setPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonEsp8266.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonEsp8266.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonEsp8266.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonEsp8266.pins.esp8266AttachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonEsp8266.category.console': 'Console',
            'microPythonEsp8266.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonEsp8266.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'ru': {
            'microPythonEsp8266.modeMenu.input': 'input',
            'microPythonEsp8266.modeMenu.output': 'output',
            'microPythonEsp8266.modeMenu.inputPullup': 'input-pullup',
            'microPythonEsp8266.levelMenu.high': 'high',
            'microPythonEsp8266.levelMenu.low': 'low',
            'microPythonEsp8266.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonEsp8266.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonEsp8266.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonEsp8266.eolMenu.warp': 'warp',
            'microPythonEsp8266.eolMenu.noWarp': 'no-warp',
            'microPythonEsp8266.category.pins': 'Pins',
            'microPythonEsp8266.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonEsp8266.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonEsp8266.pins.setPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'microPythonEsp8266.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonEsp8266.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonEsp8266.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'microPythonEsp8266.pins.esp8266AttachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonEsp8266.category.console': 'Console',
            'microPythonEsp8266.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonEsp8266.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'zh-cn': {
            'microPythonEsp8266.modeMenu.input': '输入',
            'microPythonEsp8266.modeMenu.output': '输出',
            'microPythonEsp8266.modeMenu.inputPullup': '上拉输入',
            'microPythonEsp8266.levelMenu.high': '高',
            'microPythonEsp8266.levelMenu.low': '低',
            'microPythonEsp8266.InterrupModeMenu.risingEdge': '上升沿',
            'microPythonEsp8266.InterrupModeMenu.fallingEdge': '下降沿',
            'microPythonEsp8266.InterrupModeMenu.changeEdge': '电平变化',
            'microPythonEsp8266.eolMenu.warp': '换行',
            'microPythonEsp8266.eolMenu.noWarp': '不换行',
            'microPythonEsp8266.category.pins': '引脚',
            'microPythonEsp8266.pins.setPinMode': '设置引脚 [PIN] 模式为 [MODE]',
            'microPythonEsp8266.pins.setDigitalOutput': '设置数字引脚 [PIN] 输出为 [LEVEL]',
            'microPythonEsp8266.pins.setPwmOutput': '设置 PWM 引脚 [PIN] 输出为 [OUT]',
            'microPythonEsp8266.pins.readDigitalPin': '读取数字引脚 [PIN]',
            'microPythonEsp8266.pins.readAnalogPin': '读取模拟引脚 [PIN]',
            'microPythonEsp8266.pins.setServoOutput': '设置舵机引脚 [PIN] 输出为 [OUT]',
            'microPythonEsp8266.pins.esp8266AttachInterrupt': '当引脚 [PIN] 检测到 [MODE] 时执行',
            'microPythonEsp8266.category.console': '串口',
            'microPythonEsp8266.console.consolePrint': '打印 [TEXT] [EOL]',
            'microPythonEsp8266.console.consoleInput': '提示 [TEXT] 并读取输入'
        },
        'zh-tw': {
            'microPythonEsp8266.modeMenu.input': '輸入',
            'microPythonEsp8266.modeMenu.output': '輸出',
            'microPythonEsp8266.modeMenu.inputPullup': '上拉輸入',
            'microPythonEsp8266.levelMenu.high': '高',
            'microPythonEsp8266.levelMenu.low': '低',
            'microPythonEsp8266.InterrupModeMenu.risingEdge': '上升沿',
            'microPythonEsp8266.InterrupModeMenu.fallingEdge': '下降沿',
            'microPythonEsp8266.InterrupModeMenu.changeEdge': '電平變化',
            'microPythonEsp8266.eolMenu.warp': '換行',
            'microPythonEsp8266.eolMenu.noWarp': '不換行',
            'microPythonEsp8266.category.pins': '引腳',
            'microPythonEsp8266.pins.setPinMode': '設定引腳 [PIN] 模式為 [MODE]',
            'microPythonEsp8266.pins.setDigitalOutput': '設定數位引腳 [PIN] 輸出為 [LEVEL]',
            'microPythonEsp8266.pins.setPwmOutput': '設定 PWM 引腳 [PIN] 輸出為 [OUT]',
            'microPythonEsp8266.pins.readDigitalPin': '讀取數位引腳 [PIN]',
            'microPythonEsp8266.pins.readAnalogPin': '讀取類比引腳 [PIN]',
            'microPythonEsp8266.pins.setServoOutput': '設定伺服引腳 [PIN] 輸出為 [OUT]',
            'microPythonEsp8266.pins.esp8266AttachInterrupt': '當引腳 [PIN] 偵測到 [MODE] 時執行',
            'microPythonEsp8266.category.console': '串列',
            'microPythonEsp8266.console.consolePrint': '印出 [TEXT] [EOL]',
            'microPythonEsp8266.console.consoleInput': '提示 [TEXT] 並讀取輸入'
        }
    },
    'blocks': {
        'en': {},
        'ru': {},
        'zh-cn': {},
        'zh-tw': {}
    }
};
